"""SPARCAL Spatial-SNV Viewer."""
import datetime
import os

__version__ = "1.0.0"


def build_time() -> str:
    """Best-effort build/packaging timestamp shown in the About dialog.

    Prefers a stamp written at build time (``_build_info.BUILD_TIME``, generated by
    build_macos.sh); falls back to the mtime of this source file when running from a
    checkout."""
    try:
        from ._build_info import BUILD_TIME  # type: ignore
        return str(BUILD_TIME)
    except Exception:  # noqa: BLE001
        ts = os.path.getmtime(__file__)
        return datetime.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M")
